version: '4.0'

services:
  postgres:
    image: postgres:16
    container_name: gophermartdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gophermart
    ports:
      - "5432:5432"

  gophermart:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gophermart
    environment:
      - RUN_ADDRESS=:8080
      - DATABASE_URI=postgres://postgres:postgres@postgres:5432/gophermart?sslmode=disable
      - ACCRUAL_SYSTEM_ADDRESS=http://accrual:8090
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  postgres_data: